name: Build Python app

on:
    push:
      paths:
        - 'images/icon.ico'
        - 'library/TextConverter.py'
        - 'versions/terminal_window.py'
        - 'versions/cli_args.py'
        - '.github/workflows/build.yml'
        - 'requirements.txt'
    pull_request:
    workflow_dispatch:

jobs:
    build:
        name: Build app on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: ["windows-latest", "macos-latest", "ubuntu-latest"]
        steps:
            - name: Checkout ref
              uses: actions/checkout@v4
              with:
                ref: ${{ github.sha }}

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: 3.11

            - name: Install requirements
              run: |
                pip install -r requirements.txt
                pip install pyinstaller

            - name: PyInstaller (Terminal GUI)
              run: pyinstaller --icon=images/icon.ico versions/terminal_gui.py

            - name: PyInstaller (CLI)
              run: pyinstaller --icon=images/icon.ico versions/cli_args.py

            - name: Upload Builds
              uses: actions/upload-artifact@v4
              with:
                name: ${{ matrix.os }} build at ${{ github.sha }}
                path: build/

            - name: Upload Dists
              uses: actions/upload-artifact@v4
              with:
                name: ${{ matrix.os }} dist at ${{ github.sha }}
                path: dist/
